config/routes.rb
Rails.application.routes.draw do

  root 'videos#index'

  get 'dashboard/home'
  get '/my_videos', to: 'videos#my_videos', as: 'my_videos'

  devise_for :users

  resources :videos

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :videos

  def is_owner?(video)
    video.user_id.eql?(self.id)
  end
end

app/models/video.rb
class Video < ApplicationRecord

  belongs_to :user

  mount_uploader :file, AvatarUploader

  # def set_success(format, opts)
  #   self.success = true
  # end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  # before_action :authenticate_user!
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  def home;end

end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :check_user, only: [:edit, :new, :create, :destroy]
  before_action :set_video, only: [:show, :edit, :update, :destroy]
  after_action :set_views, only: [:show]

  def index
    @videos = Video.all
  end

  def show;end

  def new
    @video = current_user.videos.new
  end

  def edit;end

  def create
    @video = current_user.videos.new(video_params)

    if @video.save
      redirect_to @video, notice: 'Video was successfully created.'
    else
      render :new
    end
  end

  def update
    if @video.update(video_params)
      redirect_to @video, notice: 'Video was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @video.destroy
    redirect_to videos_url, notice: 'Video was successfully destroyed.'
  end

  def my_videos
    @videos = current_user.videos
  end

  private
    def check_user
      return true if user_signed_in?
      redirect_to root_path, notice: 'Signup or login to access the page!'
    end

    def set_video
      @video = Video.find(params[:id])
    end

    def set_views
      @video.views += 1
      @video.save
    end

    def video_params
      params.require(:video).permit(:name, :description, :file)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper


  def flash_class(level)
    case level
    when :notice then "alert alert-info"
    when :success then "alert alert-success"
    when :error then "alert alert-danger"
    when :alert then "alert alert-warning"
    end
  end

end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/common/_flash_msg.html.erb
<% flash.each do |name, msg| %>
  <% unless msg.blank? %>
    <div class="<%= flash_class(name.to_sym) %> fade in">
      <a href="#" data-dismiss="alert" class="close">×</a>
      <%= content_tag :p, flash[name.to_sym] %>
    </div>
  <% end %>
<% end %>

app/views/common/_header.html.erb
<nav class="navbar navbar-expand-sm bg-light">
  <a class="navbar-brand" href="#">Video's</a>

  <!-- Links -->
  <ul class="navbar-nav">
    <li class="nav-item">
      <% if user_signed_in? %>
        <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "nav-link" %>
      <% else %>
        <%= link_to "Login", new_user_session_path, class: "nav-link" %>
      <% end %>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/">Home</a>
    </li>
    <% if user_signed_in? %>
      <li class="nav-item">
        <a class="nav-link" href="<%= my_videos_path %>">My Video's</a>
      </li>
    <% end %>
  </ul>
</nav>

app/views/dashboard/home.html.erb
<h1>Dashboard#home</h1>
<p>Find me in app/views/dashboard/home.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VideoUploader</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <header>
    <%= render partial: 'common/header' %>
  </header>

  <body>
    <%= render partial: 'common/flash_msg' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/videos/_form.html.erb
<%= form_with(model: video, local: true, multipart: true) do |form| %>
  <% if video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(video.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul>
      <% video.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :video_name, required: true, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :video_description, class: 'form-control' %>
  </div>

  <% unless video.persisted? %>
    <div class="field">
      <%= form.label :file %>
      <%= form.file_field :file, id: :video_file, required: true, class: 'form-control' %>
    </div>
  <% end %>
  <br><br>
  <div class="actions">
    <%= form.submit class: 'form-control btn btn-primary' %>
  </div>
<% end %>

app/views/videos/edit.html.erb
<h1>Editing Video</h1>

<%= render 'form', video: @video %>

app/views/videos/index.html.erb
<% if user_signed_in? %>
  <%= link_to 'Add Video', new_video_path, class: 'btn btn-primary pull-right' %>
<% end %>

<br>

<div class="col-md-12 videos">
  <% @videos.each do |video| %>
    <div class="col-md-5 video">
      <a href="<%= video_path(video) %>">
        <%= video_tag(video.file, controls: true, autobuffer: true, style: 'width: 100%;') %>
      </a>
      <br>
      <strong><%= video.name %></strong> (<%= video.views %> views)
      <br>
      <span><%= video.description.truncate(50) %></span>
    </div>
  <% end %>
</div>

app/views/videos/my_videos.html.erb
<%= link_to 'Add Video', new_video_path, class: 'btn btn-primary pull-right' %>

<br>

<div class="col-md-12 videos">
  <% if @videos.present? %>
    <% @videos.each do |video| %>
      <div class="col-md-5 video">
        <a href="<%= video_path(video) %>">
          <%= video_tag(video.file, controls: true, autobuffer: true, style: 'width: 100%;') %>
        </a>
        <br>
        <strong><%= video.name %></strong>
        <span><%= video.description.truncate(50) %></span>
      </div>
    <% end %>
  <% else %>
    <h3>You have not uploaded any video yet!</h3>
  <% end %>
</div>

app/views/videos/new.html.erb
<h1>New Video</h1>
<%= link_to '< Back', videos_path %>
<br><br>
<%= render 'form', video: @video %>

app/views/videos/show.html.erb
<div class="row">
  <div class="col-md-2"></div>
  <div class="col-md-8">
    <h2 class="text-center"><%= @video.name %></h2>
    <span class="pull-right"><%= @video.views %> views</span>
    <%= video_tag(@video.file, controls: true, autobuffer: true) rescue 'Temproory video is not available' %>
    <p><%= @video.description %></p>
  </div>
  <br>
  <% if (current_user && current_user.is_owner?(@video)) %>
    <div class="col-md-12 text-center">
      <%= link_to 'Edit', edit_video_path(@video) %> |
      <%= link_to 'Back', videos_path %>
    </div>
  <% end %>
</div>